# General
baseURL = "https://www.marvhock.com/"
languageCode = "en"
title = "marvhock"

# Configuration
SectionPagesMenu = "main"

# Site Params
[params]
  colors = ["yellow", "blue", "green"]

[params.pageColors]
  default = "#ececec"

[[params.social]]
  name = "GitHub"
  url = "https://github.com/marvhock"

[[params.social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/marvin-hockenjos-68b790227"

[[params.social]]
  name = "XING"
  url = "https://www.xing.com/profile/Marvin_Hockenjos/cv"
